# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36555561f3029b9c4fad4b01f29354d300e095c78359beb76f3e561f785d8de11a7fbe7db082f456e1f6a7b12c07b725495250d68ad00d42ded875b0ca184ce7

test:
  secret_key_base: 08d24744dab23e4e41ae4ddd5bebb1efe4cb793ed32035ac59b8a705c00ffc8cdf8f870828dec847ab448ed8aa30f45b2c8283f359c52c6d912141e507ca8ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
