Admin.create!([
  {email: "maxwelle.1122@gmail.com", password: "testtest"},
  {email: "andy.john.jakubek@gmail.com", password: "testtest"},
  {email: "iqover9000@gmail.com", password: "testtest"},
  {email: "zackh1998@gmail.com", password: "testtest"}
])
About.create!([
  {image_file_name: "214x140.png", image_content_type: "image/png", image_file_size: 4753, image_updated_at: "2015-10-24 19:13:32", description: "Andy Jakubek is a junior at Lake City High School in Coeur d'Alene, Idaho, and this is his second year as a member of Business Professionals of America. He loves BPA and has learned a lot of new skills in technology and leadership. Andy is also the President of the Lake City High School Key Club. He takes all Honors and AP classes, and enjoys all his activities very much.", name: "Andy Jakubek", email: "andy.john.jakubek@gmail.com", phone: "208-699-5660"},
  {image_file_name: "214x140.png", image_content_type: "image/png", image_file_size: 4753, image_updated_at: "2015-10-24 19:13:37", description: "Maxwell Evans is a junior at Lake City High School in Coeur d'Alene, Idaho, and this is his first year in Business Professionals of America. Through it he has learned more about technology and how to be an effective leader. Max is also a member of the Lake City High School cross-country and track teams. He takes several Honors and AP classes, and is an active citizen of the city and school.", name: "Maxwell Evans", email: "maxwelle.1122@gmail.com", phone: "208-819-8372"},
  {image_file_name: "214x140.png", image_content_type: "image/png", image_file_size: 4753, image_updated_at: "2015-10-24 19:13:45", description: "Zack Holbrook is a junior at Lake City High School in Coeur d'Alene, Idaho, and he has been in Business Professionals of America for 3 years. Through it he has learned more about technology and business. Zack is also a member of the Lake City High School cross-country and track teams. He takes several Honors and AP classes and enjoys learning about World History.", name: "Zack Holbrook", email: "zackh1998@gmail.com", phone: "+1 208 661 0783"},
  {image_file_name: "214x140.png", image_content_type: "image/png", image_file_size: 4753, image_updated_at: "2015-10-24 19:13:50", description: "Parker Piedmont is a junior at Lake City High School in Coeur d'Alene, Idaho, and this is his second year as a member of Business Professionals of America. He is glad to have become a part of BPA and has significantly improved his knowledge of Web site design, as well as his teamwork skills. Parker also participates in the Lake City High School cross-country and track teams, as well as multiple bands at the school. He is currently enrolled in an Honors class and 5 AP classes, and he enjoys learning about math and science.", name: "Parker Piedmont", email: "iqover9000@gmail.com", phone: "+1 208 446 8542"}
])
Credit.create!([
	{image_file_name: "214x140.png", image_content_type: "image/png", image_file_size: 4753,name:"Copyright Information", description:"The informational icons used in this site are a creation of Nick Roach and are credited to him under the GPL 2.0 and MIT licenses. The weather icons used in this site are a creation of Ali Sisk and are licensed to him under the SIL and MIT licenses. The logo animation of this site is an original creation of the developers and is credited to them, although the globe icon in the center is one of Roach's icons. The images of the developers are credited to themselves. The Business Professionals of America logo and tagline are both licensed by Business Professionals of America. All other images are licensed under the Creative Commons."},
	{image_file_name: "214x140.png", image_content_type: "image/png", image_file_size: 4753,name:"HTML5 Validation", description:"In order to make sure that we provide a user-friendly and browser-friendly viewing experience, we have designed this site to conform to the World Wide Web Consortium's HTML5 standards. Our code is validated by the W3C's HTML5 validator and has no errors in it."},
	{image_file_name: "214x140.png", image_content_type: "image/png", image_file_size: 4753,name:"Business Professionals of America", description:"This site was created by members of the Business Professionals of America, Lake City High School Chapter in Coeur d'Alene, Idaho, for the PSA themed Web Site Design Team event at the 2016 National Leadership Conference in Anaheim, California."}
])